version: '2.2'
services: 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_container
    restart: always
    ports: 
      - '15672:15672'
  consul:
    image: consul
    container_name: my_consul
  nginx:
    image: nginx
    container_name: my_nginx
  consul_template:
    image: hashicorp/consul-template
    container_name: my_consul_template